### ISSUE TITLE
registrator

### ISSUE THREAD

**Issue by gdkrmr** [gdkrmr/WeightedOnlineStats.jl#19]
@JuliaRegistrator register()

**Comment by nkottary** [comment]
You need to quote the register() bit, Ex: `register()`

**Comment by gdkrmr** [comment]
I thought it did not work because the package is already registered @JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator `register()`

**Comment by gdkrmr** [comment]
@JuliaRegistrator register()
