### ISSUE TITLE
Great job! Thanks,  small mistake at the beginning of hints fit!(WeightedMean, values, weights) not works;)

### ISSUE THREAD

**Issue by programistawpf** [gdkrmr/WeightedOnlineStats.jl#35]
Great job! I tried algebraically myself but it is beautiful! One little thing: the tutoril has a mistake at the beginning:
```
# fit using arrays:
o1 = fit!(WeightedMean, values, weights)
```
Must be: 
```
o1 = WeightedMean()
fit!(o1, values, weights)
```
Paul

**Comment by gdkrmr** [comment]
Actually `fit!` should have a return value. But you are right, that the example does not work, it should be
```
o1 = fit!(WeightedMean(), values, weights)
```

**Comment by gdkrmr** [comment]
Thanks for reporting! Corrected
