### ISSUE TITLE
allow StatsBase 0.33

### ISSUE THREAD

**Issue by tpapp** [gdkrmr/WeightedOnlineStats.jl#37]
Does the package need to depend on `StatsBase 0.32.1` explicitly, or would `0.32, 0.33` do? Is it https://github.com/JuliaStats/StatsBase.jl/issues/556?

Incidentally, please consider enabling https://github.com/bcbi/CompatHelper.jl/

**Comment by gdkrmr** [comment]
Thanks for the suggestion. One question regarding `CompatHelper.jl`: Am I supposed to use
```
[compat]
StatsBase = "0.33"
```
instead of 
```
[compat]
StatsBase = ">= 0.32.1"
```
with `CompatHelper`?

**Comment by tpapp** [comment]
My understanding is that once enabled, CompatHelper would make a PR adding comma-separated versions, eg
```toml
[compat]
StatsBase = "0.32.1, 0.33"
```
which is what you should use anyway (open-ended ranged will not be accepted in the registry).

**Comment by gdkrmr** [comment]
Ok, let's see if this works. Thanks!
